node-ip-address: 192.168.88.237 #节点/虚拟机ip
node-port: 8004
register:
  ip-address: 192.168.88.237
  port1: 8001
  port2: 8002
  port3: 8003
server:
  port: ${node-port}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的大写名称的服务
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://${register.ip-address}:${register.port1}/eureka/,http://${register.ip-address}:${register.port2}/eureka/,http://${register.ip-address}:${register.port3}/eureka/ #内网注册
  instance:
    prefer-ip-address: true
    ip-address: ${node-ip-address}
    non-secure-port: ${node-port} #外网发现的端口
    instance-id: ${eureka.instance.ip-address}:${eureka.instance.non-secure-port}
#logging:
#  level:
#    org:
#      springframework:
#        cloud:
#          gateway: debug